- import_role:
    name: Juniper.junos

- name: Execute commands on a Juniper Device to get configured interfaces
  juniper_junos_config:
    provider:
      host: "{{host}}"
      username: "{{username}}"
      password: "{{password}}"
      port: 22
    retrieve: 'committed'
    format: xml
  register: execute_command_resp
  ignore_errors: yes

- name: setting task file to juniper.yml
  set_fact:
    task_file: "roles/check_config_mode/tasks/juniper.yml"

- name: set loop_condition
  set_fact:
    loop_condition: "'failed' in execute_command_resp and execute_command_resp.failed == true"