---
- name: Get the Hardware Inventory Information by reading the Prouter object

  hosts: localhost
  gather_facts: no
  connection: local

  pre_tasks:
    - name: Include global variables
      include_vars: group_vars/all.yml
  vars:
    prouter_family: "{{playbook_input.device_family | lower}}"
    prouter_name: "{{playbook_input.device_fqname[-1]}}"

  tasks:
    - block:
        - name: Include hardware inventory role
          include_role:
            name: import_hardware_inventory_info

        - set_fact:
            output: {
                      "status": "Success",
                      "message": "Hardware inventory import for device: {{prouter_name}} successful"
                    }

        - name: Print output
          debug:
            var: output
            verbosity: 1
      when: '"junos-es" not in prouter_family'

    - block:
        - name: Set output if skipped for srx devices
          set_fact:
            output: {
                          "status": "Success.",
                          "message": "Hardware inventory skipped for srx devices"

                    }

        - name: Print output
          debug:
            var: output
            verbosity: 1
      when: '"junos-es" in prouter_family'
