---
- name: Checking if nodes are already available in Contrail-Command
  set_fact:
    output: "{{ playbook_input | check_nodes_with_cc(valid_ipmi_details) }}"

- name: DEBUG-SERVER DISCOVERY => CHECK WITH CC
  debug: var=output.final_ipmi_details

- name: Registering node with Discovery Plugin
  set_fact:
    output: "{{ playbook_input | register_nodes(output.final_ipmi_details) }}"
  when:
    - output.status is defined
    - output.status == "success"
    - output.final_ipmi_details is defined
    - output.final_ipmi_details| length > 0

- name: DEBUG-SERVER DISCOVERY => REGISTERED NODES
  debug: var=output.nodes

- name: Triggering Hardware inspection with Discovery plugin
  set_fact:
    output: "{{ playbook_input | trigger_introspect(output.nodes ) }}"
  when:
    - playbook_input.input.ironic.introspection_flag | default('yes') | bool
    - output.status is defined
    - output.status == "success"
    - output.nodes is defined
    - output.nodes | length > 0

- name: DEBUG-SERVER DISCOVERY => TRIGGERED NODES
  debug: var=output.nodes

- name: Importing nodes with Contrail-Command
  set_fact:
    output : "{{ playbook_input | import_ironic_nodes(output.nodes)}}"
  when:
    - output.status is defined
    - output.status == "success"
    - output.nodes is defined
    - output.nodes | length > 0

- name: DEBUG-SERVER DISCOVERY => IMPORTED NODES
  debug: var=output.success_nodes
