- name: Execute a basic Junos software upgrade.
  block:
    - import_role:
        name: read_re_information
      vars:
        prouter_dynamic_ip: "{{pr_host}}"
        username: "{{pr_user}}"
        password: "{{pr_password}}"
        port: "{{prouter_port}}"
        timeout: 30

    - name: disable the GRES if enabled on dual RE
      juniper_junos_config:
        load: "set"
        lines:
          - "set chassis redundancy graceful-switchover"
          - "set routing-options nonstop-routing"
          - "set system commit synchronize"
          - "deactivate chassis redundancy graceful-switchover"
          - "deactivate routing-options nonstop-routing"
        comment: "Contrail execution ID: {{ job_ctx.job_execution_id }}"
        ignore_warning: "True"
        format: "set"
        provider:
          host: "{{ pr_host }}"
          username: "{{ pr_user }}"
          password: "{{ pr_password }}"
          port: "{{prouter_port}}"
          timeout: "{{JUNOS_COMMIT_TIMEOUT | int}}"
      register: junos_response
      when : "routing_engines|length == 2"

    - juniper_junos_software:
        provider:
          host: "{{pr_host}}"
          user: "{{pr_user}}"
          password: "{{pr_password}}"
          port: "{{prouter_port}}"
        version: "{{image_os_version}}"
        vmhost: "{{vmhost_flag}}"
        reboot: true
        kwargs:
          ignore_warning: true
        remote_package: "{{downloadurl}}"
      register: junos_response
    #  ignore_errors: True
  rescue:
    - include_tasks: error_handler.yml
      vars:
        op_err_message: "Unable to upgrade image on the device. Junos upgrade task failed with exception. {{junos_response.msg}}"
        results: |
          {
            "prouter_uuid": "{{pr_uuid}}",
            "image_uuid": "{{image_uuid}}",
            "msg": "Image upgrade task failed"
          }
        jl_err_message: "Unable to upgrade image {{filename}} on the device {{pr_fqname}}. Junos upgrade task failed with exception. {{junos_response.msg}}"

- name: Print the complete response.
  debug:
    var: junos_response
    verbosity: 1

- name: Job logs for image upgrade task with percentage
  include_tasks: percentage_update.yml
  vars:
    jl_message: >
      {% if 'Reboot' in junos_response.msg -%}
        Image upgrade task completed on this device: {{junos_response.msg}}. Device reboot may take 15 to 20 mins.
      {% else -%}
       Image upgrade task completed on this device. Same version found.
      {%- endif %}

- name: Rebooting
  block:
    - name: Update prouter logs with maintenance mode status
      prouter_objectlog:
        prouter_fqname: "{{pr_fqname}}"
        onboarding_state: "{{DEVICE_STATE.REBOOTING}}"
        job_ctx: "{{job_ctx}}"

     #Delay for 60 sec and then keep checking netconf connectivity for every 60 sec(sleep). Total timeout 1200 sec
    - name: Check NETCONF connectivity after reboot
      wait_for:
        host: "{{pr_host}}"
        port: 830
        timeout: 1200
        delay: 60
        connect_timeout: 10
        sleep: 60
  when: "'Reboot' in junos_response.msg"

 #Initialize job data
- name: Append job logs after device is up with percentage
  include_tasks: percentage_update.yml
  vars:
    jl_message: >
      {% if 'Reboot' in junos_response.msg -%}
        Device is up after reboot. Now validating image version on device.
      {% else -%}
        Validating image version on device.
      {%- endif %}

- import_role:
    name: wait_for_fpc_online

- name: Append job logs with percentage
  include_tasks: percentage_update.yml
  vars:
    jl_message: "Fpc online for {{pr_vendor}} device, {{prouter_name}}"

- name: Enable the GRES if enabled on dual RE
  juniper_junos_config:
    load: "set"
    lines:
        - "activate chassis redundancy graceful-switchover"
        - "activate routing-options nonstop-routing"
    comment: "Contrail execution ID: {{ job_ctx.job_execution_id }}"
    ignore_warning: "True"
    format: "set"
    provider:
      host: "{{ pr_host }}"
      username: "{{ pr_user }}"
      password: "{{ pr_password }}"
      port: "{{prouter_port}}"
      timeout: "{{ JUNOS_COMMIT_TIMEOUT | int }}"
  register: junos_response
  when : "routing_engines | length == 2"
