import os
import platform
from distutils.version import LooseVersion

subdirs = [
    'gunit',
    'http_parser',
    'pugixml',
    'rapidjson',
    'bind',
    'hiredis',
    'rabbitmq-c',
    'SimpleAmqpClient',
    'openvswitch',
    'ipfix',
    'tbb',
    'restclient-cpp',
]

(distname, version, _) = platform.dist()
if distname in ['centos', 'redhat'] and LooseVersion(version) >= LooseVersion('7.0'):
   subdirs += [
      'gperftools',
      'log4cplus',
   ]

for dir in subdirs:
    SConscript(dirs = dir, variant_dir = '#/build/third_party/' + dir)
