- name: Update job logs with config info
  job_objectlog:
    job_ctx: "{{ job_ctx }}"
    message: "Deploying config to device '{{ device_name }}' (it may take a while)"
    device_name: "{{ device_name }}"
    status: "{{ JOBLOG_STATUS.IN_PROGRESS }}"

- name: finish with vendor-specific commit logic
  include_tasks: "{{ device_vendor }}.yml"

- name: print device response
  debug: msg="{{ device_push_response }}" verbosity=1

- name: Update job logs with device response
  job_objectlog:
    job_ctx: "{{ job_ctx }}"
    message: "{{ device_push_message_job_log }}"
    device_name: "{{ device_name }}"
    status: "{{ JOBLOG_STATUS.IN_PROGRESS }}"
    result: "{{ dev_push_response }}"

- name: Update job log with percentage
  include_tasks: percentage_update.yml
  vars:
    current_index: 1
    jl_message: "Config pushed successfully for {{ prouter_name }}"