# -*- mode: python; -*-

#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

Import('CfgmEnv')
env = CfgmEnv.Clone()

utils_scripts = [
  'add_route_target.py',
  'contrail_utils.py',
  'del_route_target.py',
  'provision_bgp.py',
  'provision.py',
  'service-policy.py',
  'chmod.py',
  'contrail',
  'contrail-version',
  'demo_cfg.py',
  'provision_control.py',
  'provision_static_route.py',
  'service-template.py',
  'demo_cmds.sh',
  'provision_encap.py',
  'provision_vgw_interface.py',
  'use_floating_pool.py',
  'contrail_veth_port.py',
  'encap.py',
  'provision_forwarding_mode.py',
  'provision_vrouter.py',
  'vncop.py',
  'create_floating_pool.py',
  'multi_tenancy.py',
  'provision_linklocal.py',
  'del_projects.py',
  'net_policy_join.py',
  'provision_mx.py',
  'service-instance.py',
  'config_db_obj_name_validate.sh',
  'config_db_obj_name_validate.py',
  'provision_analytics_node.py',
  'provision_analytics_snmp_node.py',
  'provision_analytics_alarm_node.py',
  'provision_database_node.py',
  'provision_config_node.py',
  'provision_user_defined_log_statistics.py',
  'provision_alarm.py',
  'contrail_alarm.py',
  'contrail-diff-docs.py',
  'provision_issu.py',
  'issu_process.sh',
  'qosmap.py',
  'update_default_global_qos_config.py',
  'vnc_admin_api.py',
  'provision_global_vrouter_config.py',
  'chownproj.py',
]

setup_sources_rules = []
for utils in utils_scripts:
    env.Alias('install',env.Install(env['INSTALL_EXAMPLE'], utils))
    setup_sources_rules.append(
        env.Install(Dir('.'), "#controller/src/config/utils/" + utils))

setup_test_sources = [
           'test-requirements.txt',
           '.stestr.conf',
           'tox.ini',
           '.coveragerc',
           'tests',
          ]

for file in setup_test_sources:
    setup_sources_rules.append(
        env.Install(Dir('.'), "#controller/src/config/utils/" + file))

env.SetupPyTestSuite(setup_sources_rules,
                     '/config/api-server/dist/contrail-api-server-0.1dev.tar.gz',
                     '/api-lib/dist/contrail-api-client-2004.tar.gz',
                     use_tox=True)
